### ISSUE TITLE
New Download URL

### ISSUE THREAD

**Issue by nikhiljha** [z3ntu/MonstercatConnectDownloader#1]
The old url was in the format (Line 245)

DOWNLOAD_BASE + album_id + "/download" + quality

The new url is in the format

DOWNLOAD_BASE + album_id + "/download" + quality + '&method=download' + track_id

This would be a really easy fix, and I would just add a pull request, but connect helper doesn't output the track_ids - only the album ids. This means ConnectHelper also needs to be fixed, which I have no idea how to do. Thanks!

**Comment by z3ntu** [comment]
So the download fails? Right now only albums (zip) downloads are supported, as tracks are a bit weird in general. For a track to download you need the release id AND the track id to download apparently (and I didn't try to figure out how to exactly do it yet).

**Comment by nikhiljha** [comment]
Yes, the download for an album fails. Let me get the error, I'm not near my PC right now.

**Comment by nikhiljha** [comment]
Python Error:

```
Traceback (most recent call last):
  File "downloader.py", line 246, in download
    success = download_file(download_link, self.save_dir, self.session)
  File "downloader.py", line 88, in download_file
    filename = str.replace(re.findall("filename=(.+)", r.headers['content-disposition'])[0], "\"", "")
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
```

Received (RAW)

`Requested resource not found. (404)`

So it appears that it's getting a keyerror because Monstercat is returning a 404. It is making the right request though, so I'm not sure why it's not working.

**Comment by z3ntu** [comment]
Can you send me your json file?

**Comment by nikhiljha** [comment]
I'm using your json file from the issue at the connect helper

**Comment by z3ntu** [comment]
Okay the problem is the first ID, which is the "F Minor Factory EP" which is not available for download yet but still in the "releases" view in Monstercat Connect. Try removing the first id from the json file (and I will add an error handler to the downloader)

**Comment by z3ntu** [comment]
Can you please try again with the newest version?

**Comment by nikhiljha** [comment]
Yup! It works! Thanks!
